[mongodb]
mongodb.devopspractice.fun
[catalogue]
catalogue.devopspractice.fun
[user]
user.devopspractice.fun
[cart]
cart.devopspractice.fun
[web]
web.devopspractice.fun
[redis]
redis.devopspractice.fun
[mysql]
mysql.devopspractice.fun
[shipping]
shipping.devopspractice.fun
[rabbitmq]
rabbitmq.devopspractice.fun
[payment]
payment.devopspractice.fun
[dispatch]
dispatch.devopspractice.fun
[localhost]
localhost

; [all:vars]
; ansible_password=DevOps321